# Generated by Django 4.2.6 on 2024-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default=False, max_length=255)),
                ('middlename', models.CharField(default=False, max_length=255)),
                ('lastname', models.CharField(default=False, max_length=255)),
                ('role', models.CharField(default=False, max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=5)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('subcity', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=100)),
                ('houseno', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
