# Generated by Django 4.2.6 on 2024-02-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='city',
        ),
    ]
