# Generated by Django 4.2.6 on 2024-02-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp_api', '0002_rename_address_users_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('contact', models.CharField(default=False, max_length=255)),
                ('email', models.CharField(default=False, max_length=255)),
                ('description', models.CharField(default=False, max_length=255)),
                ('logo', models.CharField(default=False, max_length=255)),
                ('reg_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_company', to='shareapp_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='share',
            fields=[
                ('sid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('minimum', models.IntegerField(default=0)),
                ('maximum', models.IntegerField(default=0)),
                ('issued_date', models.DateTimeField()),
                ('completed', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[(0, 'closed'), (1, 'open')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='shareapp_api.company')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('purchaseid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('purchased_on', models.DateTimeField()),
                ('planned_date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to='shareapp_api.users')),
                ('shareid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareid', to='shareapp_api.share')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('bid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('outstanding', models.FloatField()),
                ('bill_date', models.DateTimeField()),
                ('purchaseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='shareapp_api.purchase')),
            ],
        ),
    ]
