# Generated by Django 4.2.6 on 2024-02-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareapp_api', '0003_company_share_purchase_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
